apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: "nginx"
  tls:
    - hosts:
      - nginx-demo-k8s.piseth.dev
      - reactjs-demo-k8s.piseth.dev
      secretName: nginx-k8s-tls
  rules:
  - host: nginx-demo-k8s.piseth.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-svc
            port: 
              number: 80
  - host: reactjs-demo-k8s.piseth.dev
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: earthdx-svc
            port: 
              number: 80
