apiVersion: apps/v1
kind: Deployment
metadata:
  name: earthdx-app
spec:
  selector:
    matchLabels:
      app: earthdx-app
  template:
    metadata:
      labels:
        app: earthdx-app
    spec:
      containers:
      - name: my-app-container
        image: 69966/earthdx:78
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: earthdx-service
spec:
  type: ClusterIP
  selector:
    app: earthdx-app
  ports:
  - port: 80
    targetPort: 80
    # nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: earthdx-ingress
  # labels:
  #   app.kubernetes.io/name: myingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    # kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - kabknea.piseth.dev
    secretName: earthdx-secret
  rules:
  - host: kabknea.piseth.dev
    http:
      paths:
      # - path: /.well-known/acme-challenge/
      #   pathType: Prefix
      #   # path: "/"
      #   backend:
      #     service:
      #       name: cm-acme-http-solver
      #       port: 
      #         number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: earthdx-service
            port:
              number: 80