apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: path-based-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ingress-earthdx.piseth.dev
      secretName: ingress-host-tls-2
  rules:
    - host: ingress-earthdx.piseth.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: reactjs-service
                port:
                  number: 80
          - pathType: Prefix
            path: "/nginx"
            backend:
              service:
                name: nginx-service
                port:
                  number: 80
