- name: Create Master Machines
  hosts: localhost
  any_errors_fatal: true
  vars_files:
    - ../vars/machines.yaml
  tasks:
    - name: Create All Masters
      import_tasks: tasks/create-masters-task.yaml
